### ISSUE TITLE
[Error thrown] NRE on first use of a remnant item

### ISSUE THREAD

**Issue by JohnMetroid** [KawaiiBone/LethalCompanyRemnants#48]
Hey there,

I meant to report this one before in case it lead to any issues, but as far as I can tell this one might be harmless.  When picking up a remnant item and attempting to use it for the first time, an NRE will be thrown.  For items that are continually used such as flashlights, it appears to be thrown every frame until it's turned off.  For items that have a one-time interact, it appears to be thrown only once on a single frame.

It appears to stop after the first use.  Again, as far as I can tell it doesn't lead to any major issues, but I haven't tested extensively across all equipment so I figured I'd log it here for you.

![image](https://github.com/user-attachments/assets/5619e631-b131-46d3-b066-d382c6b02cc1)

**Comment by KawaiiBone** [comment]
I cannot seem to reproduce this issue, could you elaborate on the circumstances? 
Were you the host or just a player?

Thank you for this issue report.

**Comment by JohnMetroid** [comment]
I was the host. I've seen it in solo games and in multiplayer games.  It only shows on the console for the player activating the item.  I will try to look into the reproducibility of the error when I have some time.

edit: of course, when I go to repro it I can't get the error to happen.  I will keep an eye out for it and update you when I have clear steps to trigger it.  There's a good chance it's harmless, so I wouldn't worry about it for now. :)

**Comment by KawaiiBone** [comment]
This issue should now be fixed on the current new update.

I will leave this issue open for a couple of weeks so that any issues found about this, can be reported here.

**Comment by JohnMetroid** [comment]
don't see any obvious NRE issues in the new version, so closing this.  If something pops up I'll let you know

**Comment by JohnMetroid** [comment]
this bug is still present, but it's entirely unclear to me how to reproduce it.  I just saw it from a regular flashlight remnant, throwing every frame the flashlight was on during first usage.  At which point, it never shows up again.

Going to leave this one open in the hopes of nailing down reproducibility soon.  In the meantime I wouldn't worry about it, since it doesn't seem to be causing any major issues

```
[07:54:46.8999512] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[07:54:46.9169551] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[07:54:46.9329587] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[07:54:46.9509628] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[07:54:46.9669664] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)
```

**Comment by KawaiiBone** [comment]
That is strange, could you send me the profile code?
So I can test it with all the mods, that you were using.

Thank you for the issue report.

**Comment by JohnMetroid** [comment]
Sorry for the (extremely) late reply.  I hadn't been keeping up with Lethal mods for a bit, and I didn't want to send you on a wild goose chase if I didn't have anything concrete.

When testing mods today, I managed to see it with a remnant flashlight that was in the first room on experimentation.  Perhaps it will be reproducible (I don't think I have a method to load specific seeds)

<img width="964" height="252" alt="Image" src="https://github.com/user-attachments/assets/7df6f6a7-75e1-430a-97bf-9e72609fe16c" />

profile code: 01981297-139b-5ba7-6904-290acceb7a74
seed:
```
[09:32:03.5242043] [Info   :CullFactory] FracturedComplexFlow has finished generating with seed 90266065.
```
